services:
  lane-detection:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_NAME: ${REPO_NAME:-LaneDetection}
        USER_NAME: ${USER_NAME:-kujira}
        GROUP_NAME: ${GROUP_NAME:-kujira}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-7.5 8.0 8.6 8.9+PTX}
    image: lane-detection:latest
    volumes:
      - ../:/home/kujira/workspace/${REPO_NAME:-LaneDetection}
      - ./.bash_history:/home/kujira/.bash_history
    tty: true
    stdin_open: true
    network_mode: 'host'
    working_dir: /home/kujira/workspace/${REPO_NAME:-LaneDetection}
    command: ["bash"]
